apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080         # Port to access the service internally
      targetPort: 8080  # Port your application is listening on inside the container
      nodePort: 9090 # Port to access the service externally on each node
  selector:
    app: your-app-label   # Label selector to match your application deployment
